# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-12 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Special',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text=b'Limited to 250 characters.', max_length=250)),
                ('day_offered', models.IntegerField(choices=[(0, b'Monday'), (1, b'Tuesday'), (2, b'Wednesday'), (3, b'Thursday'), (4, b'Friday'), (5, b'Saturday'), (6, b'Sunday')])),
            ],
            options={
                'ordering': ['day_offered'],
                'verbose_name_plural': 'Specials',
            },
        ),
    ]
