# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-12 10:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreadSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Bread schedules',
            },
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(help_text=b'Limited to 50 characters.', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text=b'Limited to 250 characters.', max_length=250)),
                ('slug', models.SlugField(help_text=b'Suggested value automatically generated from name. Must be unique.', unique=True)),
                ('description', models.TextField(blank=True, help_text=b'A brief description of the item. No HTML is allowed.')),
                ('one_off_price', models.DecimalField(blank=True, decimal_places=2, help_text=b"Use if item isn't available in different sizes. Amount cannot be larger than five digits. Don't use a dollar sign.", max_digits=5, null=True)),
                ('status', models.IntegerField(choices=[(1, b'Live'), (2, b'Draft')], default=2)),
                ('photo', models.ImageField(blank=True, height_field=b'height', help_text=b'Please use JPG or PNG formats. Will populate the width and height fields on save.', upload_to=b'images/menu/photos', width_field=b'width')),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('is_flourless', models.BooleanField(default=False)),
                ('is_vegan', models.BooleanField(default=False)),
                ('vegan_option_available', models.BooleanField(default=False)),
                ('flourless_option_available', models.BooleanField(default=False)),
                ('is_seasonal', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name_plural': 'Items',
            },
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('category_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='categories.Category')),
            ],
            options={
                'verbose_name_plural': 'Item types',
            },
            bases=('categories.category',),
        ),
        migrations.CreateModel(
            name='ItemTypeGroup',
            fields=[
                ('category_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='categories.Category')),
                ('item_types', models.ManyToManyField(help_text=b'Select the item types you want to group together.', to='menu.ItemType')),
            ],
            options={
                'verbose_name_plural': 'Item type groups',
            },
            bases=('categories.category',),
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(help_text=b'Limited to 100 characters. Use either numerical or text-based characters.', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, help_text=b"Amount cannot be larger than five digits. Don't use a dollar sign.", max_digits=5)),
                ('description', models.TextField(blank=True, help_text=b'A brief description of the size. No HTML is allowed.')),
            ],
            options={
                'ordering': ['price'],
                'verbose_name_plural': 'Sizes',
            },
        ),
        migrations.AddField(
            model_name='itemtype',
            name='size',
            field=models.ManyToManyField(blank=True, to='menu.Size'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.ItemType'),
        ),
        migrations.AddField(
            model_name='breadschedule',
            name='bread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Item'),
        ),
        migrations.AddField(
            model_name='breadschedule',
            name='days_available',
            field=models.ManyToManyField(to='menu.Day'),
        ),
    ]
