language: python

python:
  - "3.5"

env:
  - DJANGO_SETTINGS_MODULE=caminobakery.settings.test

install:
  - pip install -r requirements.txt

# command to run tests, e.g. python setup.py test
script:
  python caminobakery/manage.py test
