# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-12 10:21
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text=b'Limited to 250 characters. Will also be used for alt text.', max_length=250)),
                ('slug', models.SlugField(help_text=b'This field will automatically populate from the title.', unique_for_date=b'uploaded')),
                ('photo', models.ImageField(height_field=b'height', help_text=b'Please use JPG or PNG formats. Will populate the width and height fields on save.', upload_to=b'images/photos', width_field=b'width')),
                ('uploaded', models.DateTimeField(default=datetime.datetime.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('caption', models.TextField(blank=True, help_text=b'A brief description of the photo. No HTML is allowed.')),
                ('one_off_photographer', models.CharField(blank=True, max_length=100)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('alt_text', models.CharField(help_text=b"Limited to 100 characters. Used for displaying text in case image isn't viewable.", max_length=200)),
                ('external_url', models.URLField(blank=True, help_text=b'If the photo is located on an external website, please add the URL here.')),
                ('status', models.IntegerField(choices=[(1, b'Live'), (2, b'Draft')], default=2, help_text=b"Only photos with a status of 'live' will be displayed publicly.")),
                ('photographer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded'],
                'verbose_name': 'photo',
                'verbose_name_plural': 'photos',
            },
        ),
    ]
