# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-12 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default=b'', help_text=b'Limited to 200 characters. Plain text only.', max_length=200)),
                ('link', models.URLField(blank=True, default=b'', help_text=b'Optional. Used to link the entire announcement.')),
                ('is_public', models.BooleanField(default=False, help_text=b'Determines if announcement is displayed on the website.')),
                ('created', models.DateTimeField(auto_now_add=True, help_text=b'Timestamp when this announcement was created.')),
            ],
        ),
    ]
