# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-12 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text=b'Limited to 50 characters.', max_length=50)),
                ('slug', models.SlugField(help_text=b'Suggested value automatically generated from title.')),
                ('description', models.TextField(blank=True, help_text=b'A brief description of the content being categorized. No HTML is allowed.')),
                ('lead_image', models.ImageField(blank=True, height_field=b'lead_image_height', help_text=b'Upload an image to display as the lead image on the template. Image must be cropped for display at 1170px wide, 400px tall. Please use JPG or PNG formats. Will populate the width and height fields on save.', upload_to=b'images/lead_images', width_field=b'lead_image_width')),
                ('lead_image_width', models.PositiveIntegerField(blank=True, null=True)),
                ('lead_image_height', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['title'],
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
